### ISSUE TITLE
HTTP 422 when unboosting a toot in the local column

### ISSUE THREAD

**Issue by DirtyF** [n1k0/tooty#100]
OK, this one is not easy reproductible (sorry guyz) but has happen many times during my tests and is minor.

When I boost a toot
Then I unboost that same toot in the third column
Then an HTTP 422 error message is displayed
Then Toot states differ between the first and third column

![422](https://cloud.githubusercontent.com/assets/103008/25536512/69c64aa8-2c3b-11e7-9c16-e444471ed2ce.png)

**Comment by DirtyF** [comment]
I can still reproduce this issue . 

Is the code automatically deployed to GitHub after each commit?

**Comment by n1k0** [comment]
Yes it is. Also, this works for me.

![test](https://cloud.githubusercontent.com/assets/41547/25649768/9c333834-2fd8-11e7-90f5-ac0cca3490d8.gif)

Have you tried force-refreshing the page (ctrl-shift-r)?

**Comment by n1k0** [comment]
Same with boost/unboost

![test](https://cloud.githubusercontent.com/assets/41547/25649863/2541c85c-2fd9-11e7-8151-6820809286fb.gif)

**Comment by n1k0** [comment]
Ok it was in the thread view, which should be fixed by #123.
