### ISSUE TITLE
Error 403 when I try to boost a private message

### ISSUE THREAD

**Issue by nicosomb** [n1k0/tooty#133]
![capture d ecran 2017-05-05 a 11 50 32](https://cloud.githubusercontent.com/assets/121870/25740986/2284b76c-3189-11e7-9110-edb36acf565e.png)

This error happens when I clicked on "Boost" for a direct message.

**Comment by n1k0** [comment]
Means we should disable the Boost button for direct messages. Is there other visibilities where boosts are forbidden?

**Comment by nicosomb** [comment]
I don't know. Can we have this information in the mastodon API?

**Comment by n1k0** [comment]
This is not mentioned in their docs, so we'll have to figure that out by ourselves :/

**Comment by nicosomb** [comment]
After my tests, you can't boot private and direct messages.

**Comment by n1k0** [comment]
Thanks for your tests, here are the results from the official client:

![](http://i.imgur.com/qYwcaJB.png)

Means we should disable reboosts for direct and private toots.

**Comment by n1k0** [comment]
Note that I'm surprised we can actually reboost an *unlisted* message. Oh well.
