### ISSUE TITLE
Refresh display after action on notifications

### ISSUE THREAD

**Issue by DirtyF** [n1k0/tooty#140]
### Current behaviour

When I try to {boost|favorite} a toot in notifications
Then a 422 HTTP error is displayed

When I remove a toot in the notifications
Then toot is removed but still displayed

When I try to {boost|favorite} a deleted toot in notifications
Then a 404 HTTP error is displayed

![tooty-fav-notif](https://cloud.githubusercontent.com/assets/103008/25772116/8aba2ae4-3263-11e7-9885-c04c31b19555.png)

**Comment by n1k0** [comment]
Hmm, can't reproduce. Do you have a sample reproducible scenario?

**Comment by DirtyF** [comment]
![error-notifications](https://cloud.githubusercontent.com/assets/103008/25773009/3225a8f0-3276-11e7-8bbd-addc070ab67c.gif)

**Comment by DirtyF** [comment]
It has deleted the toot so actions seems to work, but display is not refreshed.

**Comment by n1k0** [comment]
I see. i'm on it.
