### ISSUE TITLE
Content overflow on first column

### ISSUE THREAD

**Issue by DirtyF** [n1k0/tooty#157]
As more and more options are available in the post column, I experienced a content overflow : I had downloaded a file and after adding a spoiler and a media in a reply I couldn't scroll down to the Toot button. After hiding the download bar I could reach the call to action again.

I took a screenshot, you can see that the last group of buttons overflow from the first column:

![toot-overflow](https://cloud.githubusercontent.com/assets/103008/25961075/446654fe-3679-11e7-8851-1643eaca0c26.png)

**Comment by nicosomb** [comment]
Same bug as https://github.com/n1k0/tooty/issues/91. It was fixed but it reappeared.

**Comment by foxmask** [comment]
Hi,
I dont know if it's the same behavior but if I dont reduce the display size to 90% (same w/ chorme and firefox); the buttons are not completly displayed.

![sans titre](https://cloud.githubusercontent.com/assets/208212/25999467/802aed90-3725-11e7-833b-b3a5467c5221.png)

**Comment by DirtyF** [comment]
@nicosomb if we had a `timeline` class to the `panel-body`, than scollbar appears when there is a content overflow. Would that be an acceptable fix ?

![overflow-y](https://cloud.githubusercontent.com/assets/103008/26003785/fe2ae232-3733-11e7-9134-22e65c0280e5.gif)

**Comment by n1k0** [comment]
I think we should use media queries to conditionally set overflow rules depending on the viewport width. Also, we should work on a proper mobile view, but that's another more complicated story (#79).

**Comment by DirtyF** [comment]
@n1k0 I confess it's a dirty and lazy hack, I think using `css-grid` could also help with mobile view.

**Comment by franck-tomek** [comment]
@n1k0 Easy (and dirty) fix:
add `overflow-y: auto;
overflow-x: hidden;
max-height: calc(100vh - 65px);
overflow: hidden;
overflow-y: scroll;` to .panel-body

**Comment by n1k0** [comment]
Ok https://github.com/n1k0/tooty/commit/d5f69c18fde25bcc44fd821f3f5a69715fb0c965 will do for now, we'll get proper mobile support later.
