### ISSUE TITLE
How to logout ? 

### ISSUE THREAD

**Issue by valentin2105** [n1k0/tooty#159]
Hi,

It would be great if we can logout from the Tooty interface.

**Comment by Hexalyse** [comment]
I don't know if there is a "logout" button/function on Tooty, but you can revoke app permissions from your Mastodon account here : https://your.instance.address/oauth/authorized_applications

**Comment by n1k0** [comment]
Related: #40

**Comment by n1k0** [comment]
Fixed in https://github.com/n1k0/tooty/commit/92b9e53b8f4d92e1abf0f1ce50687c7e23a78de1
