### ISSUE TITLE
Search funtionnality

### ISSUE THREAD

**Issue by Hexalyse** [n1k0/tooty#160]
I think having a search functionality to search for users and hashtags, like there is above the toot textbox in the official web client, would be nice.

**Comment by nicofrand** [comment]
The search feature on the official client also allows to open a toot with its link.
This would be nice too : we could follow a toot when given its URL, from tooty's nice interface.

**Comment by n1k0** [comment]
#188 has been deployed to prod, feedback would be greatly appreciated.
