### ISSUE TITLE
"Spoiler" feature should keep the original "CW" name

### ISSUE THREAD

**Issue by gordonzola** [n1k0/tooty#161]
The Mastodon project has been designed with social and human values in mind, mainly to fix design failures from the birdsite, that permit harassment and intrusive behaviours. Content Warnings has been used for years in different communities, and give the possibility for readers to decide if they want to see the content, knowing its category.

Of course, spoilers can be a way to use content warnings, but we must keep in mind that this is not the original design. And people that want, or *need* content warnings in order to feel safe in a social network should know that the software give them this possibility. People that actually use CW feature for spoilers will not be embarrassed to do it, but in the contrary, a "Spoiler" button can’t let people know that this feature exists to keep them safe.

So, I suggest that the Tooty interface renames its "Spoiler" feature to "CW"

**Comment by vjousse** [comment]
To me, this "CW" acronym is just bad. It took me a lot of time to get the meaning of "CW" (as a non native English speaker).
"Spoiler" seemed a lot clearer than "CW" to me, but I get your point about "Spoiler" being only a subset of what "CW" means.

I would be ok to rename "Spoiler", but not to "CW" as it only targets the people who "already know". Maybe using the full "Content Warning" words could be enough here.

**Comment by n1k0** [comment]
@vjousse haha, great minds think alike.
