### ISSUE TITLE
render limited to the first column with Firefox mobile

### ISSUE THREAD

**Issue by foxmask** [n1k0/tooty#163]
!hi, 

[tmp_9553-screenshot_20170512-123302459436951](https://cloud.githubusercontent.com/assets/208212/25994781/90eca42c-370f-11e7-92d9-11f301bf1892.png)

![](https://cloud.githubusercontent.com/assets/208212/25994781/90eca42c-370f-11e7-92d9-11f301bf1892.png)

We cant Scroll at right or at the bottom

Regards

**Comment by DirtyF** [comment]
duplicates #79
