### ISSUE TITLE
Black screen after authorizing tooty to access to mastodon 

### ISSUE THREAD

**Issue by foxmask** [n1k0/tooty#165]
after the login page and the "authorize" button from mastodon, the return url leads to a black page with this url

    https://n1k0.github.io/tooty/?code=<a code>

I imagined to return to the "standard" render of the tooty app with all the columns.

**Comment by nicosomb** [comment]
As I said on @n1k0 on IRC, I had this bug too (and I forgot to open a new issue).

**Comment by n1k0** [comment]
I've played quite some time with the multi-account feature and can't reproduce this issue at all. I'd like to gather more information, like errors in the console, failed HTTP requests, browser versions, platform etc.

**Comment by foxmask** [comment]
how do we logout from tooty ? to make another try with this workflow

**Comment by n1k0** [comment]
By using the Logout links in the account selector

![](http://i.imgur.com/IXNES6p.png)

**Comment by foxmask** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/208212/26032369/1c880430-3892-11e7-85b4-abcd6d41210a.png)

on debian

**Comment by n1k0** [comment]
no code in the url? anything in the browser console?

**Comment by foxmask** [comment]
no I drop the code by myself :)
here is the console : 
![sans titre](https://cloud.githubusercontent.com/assets/208212/26032395/ee1f7eba-3892-11e7-87ff-2ee9ba898944.png)
![sans titre2](https://cloud.githubusercontent.com/assets/208212/26032396/ee205ae2-3892-11e7-83df-cd1de971e24f.png)

**Comment by n1k0** [comment]
Looks all fine. Very strange, I'm using the exact same version of Firefox though on Ubuntu and cannot reproduce this behavior. I don't know what to do here.

**Comment by foxmask** [comment]
It's not so annoying , for myself. 
I drop the code After that or just reload the page to continue.

**Comment by oncletom** [comment]
I encountered this issue and here is the worklow:

1. I was logged out frampiaf.org (never logged in with Firefox so far)
2. I land on https://n1k0.github.io/tooty/
3. I type `https://framapiaf.org` as a Mastodon server
4. I log in and authorize the app
5. I am being redirected on `https://n1k0.github.io/tooty/?code=...`
6. then nothing

I sort of remember following the same workflow on Chrome but the `?code=...` bit was cleared out when step 6 was reached. Nothing in the console. Maybe a different way to handle query string and stuff? An Elm bug/missed subscription?

**Comment by oncletom** [comment]
Interestingly enough.

When `?code=...` appears in the URL, the state of `tooty.clients` is the following:

```json
"[{"server":"https://framapiaf.org","token":"<sha256 value ...>","account":null}]"
```

When I refresh the page, `account` gets populated:

```json
[
    {
        "server": "https://framapiaf.org",
        "token": "<sha256 value ...>",
        "account": {
            "acct": "oncletom",
            "avatar": "https://framapiaf.org/system/accounts/avatars/000/020/824/original/a98ebd7a693ab21d.jpg?1494854750",
            "created_at": "2017-05-15T13:21:17.003Z",
            "display_name": "Thomas Parisot",
            "followers_count": 10,
            "following_count": 14,
            "header": "https://framapiaf.org/headers/original/missing.png",
            "id": 20824,
            "locked": false,
            "note": "<p></p>",
            "statuses_count": 9,
            "url": "https://framapiaf.org/@oncletom",
            "username": "oncletom"
        }
    }
]
```

From now on, if I press _Back_ in Firefox navigation button to go back to the OAuth Authorisation page, _authorise_ again, I reach the Tooty's `?code=...` page again but this time, when I refresh, the app is stuck in the state describe by @foxmask.

This, in spite of having the `tooty.clients` localStorage value being populated. When I remove the `?code=...` part in the URL, the app works as expected.
