### ISSUE TITLE
Remember the View state (for when I come back)

### ISSUE THREAD

**Issue by oncletom** [n1k0/tooty#172]
First, a big thank for creating such an easy to use webapp :-)

# Scenario

* In the _Notifications view_, I click on the _Mentions_ filter button
* When I quit the app and come back later, I expect the _Notifications view_ to be filtered by _Mentions_ unless I change the view filter state

Likewise for the _Timeline_ view (Local timeline / Global timeline / etc.).

# Suggestion 

I could even suggest mob programming this feature during [Sud Web](https://sudweb.fr/2017/) to teach/encourage open source collaboration as well as diving into Elm.

**Comment by lionelB** [comment]
I know some people that should be are interested 😄

**Comment by n1k0** [comment]
> I could even suggest mob programming this feature during Sud Web to teach/encourage open source collaboration as well as diving into Elm.

Ah, you edited that! I have half of the patch in a branch already haha.
