### ISSUE TITLE
Upgrade for 2.0 API?

### ISSUE THREAD

**Issue by bnjbvr** [n1k0/tooty#196]
Hi! I think there was a breaking change in the Mastodon API for 2.0, now ids can be BigInt instead of simple ints. It seems this entirely breaks Tooty with assertions flashing on screen and then quickly disappearing. If sometimes had time to look into it, or point me to the files that would need a change, that'd be great, thanks :)

**Comment by n1k0** [comment]
From https://github.com/tootsuite/mastodon/releases/tag/v2.0.0:

> All id attributes in the REST API responses, including attributes that end in _id, are now returned as strings instead of integers

I'm gonna look into that, thanks for the report.

**Comment by n1k0** [comment]
A pending fix is available at #197, testing and feedback are welcome.
