### ISSUE TITLE
Break src/Mastodon into a elm module?

### ISSUE THREAD

**Issue by CosineP** [n1k0/tooty#201]
im working on a mastodon elm thing and i was searching for other mastodon elm things and found this with very nice deserializers for the mastodon objects which is quite nice and i was thinking oh, hey, this could totally be an elm lib, and i was wondering if yall intended to do that

and if not, if i could do that

also side note i noticed yall have the streaming objects what elm lib are you using to stream? ill try to figure it out myself but thought id ask thanks

**Comment by n1k0** [comment]
I must confess I have totally abandoned this project for months, as I don't much use Mastodon anymore. Extracting out the Mastodon module as a separate standalone package was a plan for some time, and AFAICR it shouldn't be too hard to do just that. "Someone" would "just" have to upgrade Tooty to Elm 0.19, extract and release the Mastodon as an external package and update the Tooty codebase to depend on it.

Well that's a bunch of stuff to do for something I don't use anymore. I'd gladly accept any help with this.

For the stream API it's been reverse engineered by studying network communication using the official Web client. We're using the elm 0.18 WebSocket module, which is sadly gone in 0.19, which is another problem to solve...

**Comment by CosineP** [comment]
thank you! i may look into it
