### ISSUE TITLE
Change model fields to camelCase

### ISSUE THREAD

**Issue by vjousse** [n1k0/tooty#25]
Lots of model fields are in snake_case, even if they come from Json, they should be converted to camelCase.

**Comment by n1k0** [comment]
I don't know, it's kind of convenient to keep the names exposed by the API, that avoids a mental conversion which doesn't bring much on the table methinks.

**Comment by vjousse** [comment]
Well, I had to do the conversion from camelCase (in my head used to Elm code) to the snake_case of the model. As far as I'm aware of, I've never seen any Elm code with snake_case convention (even coming from an API).

**Comment by n1k0** [comment]
I think that's been done now.
