### ISSUE TITLE
I cannot find a `MediaRequestBody` type

### ISSUE THREAD

**Issue by n8chz** [n1k0/tooty#253]
Tried downloading and running this. First failure was date-format. Got past that hurdle with [trick from pgit19](https://github.com/ryan-haskell/date-format/issues/40#issuecomment-2003308467). Now it says
```
Detected problems in 1 module.
-- NAMING ERROR ------------------------------------------------ src/Command.elm

I cannot find a `MediaRequestBody` type:

758| updateMedia : Maybe Client -> String -> MediaRequestBody -> Cmd Msg
```

**Comment by vjousse** [comment]
Thanks for the issue, it should be fixed in #254
