### ISSUE TITLE
Extra slash in oauth URL

### ISSUE THREAD

**Issue by n8chz** [n1k0/tooty#255]
I'm trying to use this from localhost:3000 (the default) to https://cambrian.social/ (a GoToSocial instance). It can't connect to log in. The URL it uses (aside from the client_id parameter) is

`https://cambrian.social//oauth/authorize?response_type=code&client_id=XXXXXXXXXXXXXXXXXXXXXXXXXX&scope=read%20write%20follow&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F`

After modifying this in the address bar to

`https://cambrian.social/oauth/authorize?response_type=code&client_id=XXXXXXXXXXXXXXXXXXXXXXXXXX&scope=read%20write%20follow&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F`

I am able to log in and authorize the app (Tooty), but now I get an orange popup with the header `HTTP 200 : Failed decoding JSON:` followed by a very large array in JSON format which appears to be a Fediverse timeline. I would provide a pastebin, but apparently it contains NSFW content. At the bottom of this long JSON document it says `Expecting null`. I suspect this may be a problem with GoToSocial, which perhaps encodes JSON in some way that is incompatible with Tooty.

Works perfectly with my Mastodon account, though. My compliments to the chef!

**Comment by vjousse** [comment]
Indeed, tooty has only been tested with Mastodon as for now. I could have a look if you want, could I get an account on cambrian.social?

**Comment by n8chz** [comment]
Oh, wow, thanks. Certainly. Credentials in email to address on your github profile.

**Comment by vjousse** [comment]
Fixed in 140a764

I've opened another issue to track GoToSocial support https://github.com/n1k0/tooty/issues/256
