### ISSUE TITLE
Can't reveal two occurences of a same status image

### ISSUE THREAD

**Issue by n1k0** [n1k0/tooty#30]
Here I can't reveal the second image on the right. That's because the two ids are the same, we'll probably need to append some random large int to each.

![](http://i.imgur.com/vudApRU.png)

**Comment by n1k0** [comment]
Another occurence of the issue with CW:

![pb](https://cloud.githubusercontent.com/assets/41547/25312380/d99da9f2-2817-11e7-9881-619a0b000fc1.gif)

**Comment by nicosomb** [comment]
Why don't just add the timeline name in the `id` (`home-spoiler758962`) ?

**Comment by n1k0** [comment]
Yeah good idea, much more simple :+1:
