### ISSUE TITLE
Revoking the token doesn't force tooty to re-authenticate

### ISSUE THREAD

**Issue by j0k3r** [n1k0/tooty#40]
I revoked my token to debug a thing and tooty doesn't ask me to re-authorize the app.
Instead I have a just some errors.

![image](https://cloud.githubusercontent.com/assets/62333/25331811/a2dab81a-28e4-11e7-8215-e18aba9aa791.png)

I needed to clear storage on my browser to be able to get the authenticate screen again

**Comment by n1k0** [comment]
Yeah, we should add a proper logout link at some point to clear all stored auth information.

**Comment by n1k0** [comment]
Fixed in https://github.com/n1k0/tooty/commit/92b9e53b8f4d92e1abf0f1ce50687c7e23a78de1
