### ISSUE TITLE
Display private messages in a different way

### ISSUE THREAD

**Issue by nicosomb** [n1k0/tooty#58]
![capture d ecran 2017-04-25 a 16 54 51](https://cloud.githubusercontent.com/assets/121870/25392048/ee3beea2-29d7-11e7-9122-87528cf2792c.png)

The first message is a private message, the second one is a public message. 
Private messages should be more visible.

**Comment by n1k0** [comment]
We could add dedicated icon, a little like what the official client does, but in a more visible fashion. We could also use distinct background colors, though as a colorblind person myself I don't think that's enough 😉

**Comment by vjousse** [comment]
As mentionned here https://pad.lqdn.fr/p/suggestions_mastodon I think we should add an optional "column" for private messages.
Mixing public/private messages in the same column is a disaster to come.

**Comment by n1k0** [comment]
I've added a new filter button in the notifications timeline to just get direct messages (https://github.com/n1k0/tooty/commit/93e42ac5751243e16a964a44daafd2c6c9119984). Works surprisingly well for me, so I didn't go as far as filtering them in the home timeline, though we may revisit this according to feedback.
