### ISSUE TITLE
Intermittent WebSocket error: Expecting a String at _.payload but instead got <Int>

### ISSUE THREAD

**Issue by n1k0** [n1k0/tooty#59]
![](http://i.imgur.com/V8kM02d.png)

Sadly I couldn't catch the faulty incoming message. /cc @vjousse

**Comment by vjousse** [comment]
It's really strange. Some `payload` are in fact int values?
As the API is not documented, it's pretty hard to debug. We need to keep our Dev Tools open :-)

**Comment by n1k0** [comment]
Happening again...

![](http://i.imgur.com/zcaJJhQ.png)

How do you usually debug WS in the browser? Been a while I didn't do that.

**Comment by vjousse** [comment]
Ahah. I don't. I've never done that (Elm is my first time as a frontend dev).
I add a Debug.log below this line https://github.com/n1k0/tooty/blob/master/src/Model.elm#L542
`d = Debug.log "[WS Message] " message` and "roule ma poule !"

**Comment by n1k0** [comment]
Haha, well I'll be deploying this so we can inspect things on production. RACHE MODE, HERE WE COME.

**Comment by n1k0** [comment]
Another interesting one:

![](http://i.imgur.com/oI7jemO.png)

So we also receive status deletion notifications.

**Comment by vjousse** [comment]
Nice! I suppose I will have to go through the Ruby code to check for the other possibilities.

**Comment by n1k0** [comment]
I'm gonna handle these deletion events.

**Comment by n1k0** [comment]
Closed by #69.
