### ISSUE TITLE
Allow posting a status :)

### ISSUE THREAD

**Issue by n1k0** [n1k0/tooty#6]
I'm on it.

![screenshot at 15 58 22](https://cloud.githubusercontent.com/assets/41547/25234424/529ad0ce-25e2-11e7-8459-37f9bcea1174.png)

**Comment by nicosomb** [comment]
I think that the first column is not mandatory. Or maybe something like tweetdeck, which is hidden by default. 

Or just a `+` button in the header which opens a new popin with the form.

**Comment by n1k0** [comment]
Yeah, maybe, that's a little early, I'd just like to add the ability to post something first. Here's the whole layout:

![screenshot at 16 02 09](https://cloud.githubusercontent.com/assets/41547/25234576/cbf925ba-25e2-11e7-8463-7159f1fa35e8.png)
