### ISSUE TITLE
Status HTML entities are not properly decoded 

### ISSUE THREAD

**Issue by n1k0** [n1k0/tooty#8]
As reported by @nicosomb 

![screenshot at 16 36 03](https://cloud.githubusercontent.com/assets/41547/25236169/78ad6dda-25e7-11e7-99df-4a8c07dd4995.png)

**Comment by nicosomb** [comment]
I can confirm that the bug comes from the lib. 

https://jinjor.github.io/elm-html-parser/

If you type `&amp;`, the  `&` is well displayed. 
If you type '&apos;`, the `'` is wrong displayed.

**Comment by n1k0** [comment]
Meanwhile we could probably replace all `&apos;` with an apostrophe in the HTML string, what do you think?

**Comment by vjousse** [comment]
It seems that there is another strange behavior, and I'm not talking of Cheminade here 🤣 
![gt](https://cloud.githubusercontent.com/assets/154904/25246861/516e51a4-2609-11e7-83b7-39f7aebf883a.png)

**Comment by n1k0** [comment]
We should probably check for all these http://www.madore.org/~david/computers/unicode/htmlent.html
