### ISSUE TITLE
Global timeline option not used when closing a thread

### ISSUE THREAD

**Issue by bacardi55** [n1k0/tooty#93]
Steps to reproduce:
- Check the "4th column renders the global timeline"
- 3rd column is now global timeline
- I click on a toot to display the conversation on the 4th column
- I close the conversation (via the "x" at the top right)

Issue:
- The local timeline is displayed

Expected:
- The global timeline should be displayed as the checkbox is still checked for global timeline.

**Comment by vjousse** [comment]
I'm on it.
