### ISSUE TITLE
Insert emojis

### ISSUE THREAD

**Issue by DirtyF** [n1k0/tooty#95]
I can easily insert emojis (à la Slack and/or à la Twitter)

As a user accustomed to Slack UX
When I type `:` and two chars 
Then a list a corresponding emojis are displayed
And I can select one to enter an emoji 

As a user accustomed to Twitter UX
When I click the emoji icon near the input
Then a list a corresponding emojis are displayed
And I can search to select an emoji I want to insert in my toot

![image](https://cloud.githubusercontent.com/assets/103008/25531561/7b8e67c2-2c2a-11e7-9bd6-fb0f819280bd.png)

**Comment by vjousse** [comment]
Partially fixed in https://github.com/n1k0/tooty/issues/216
