### ISSUE TITLE
Delete toots

### ISSUE THREAD

**Issue by DirtyF** [n1k0/tooty#97]
As a user
I can delete my own toots

**Comment by DirtyF** [comment]
When I delete a toot in a thread
Then the column view is not refreshed
As someone who thinks the toot was not deleted
When I try to delete the toot again
Then a 404 HTTP Error is displayed

![tooty-delete](https://cloud.githubusercontent.com/assets/103008/25580362/b1445ec8-2e80-11e7-9ef3-4fd3d15c68b4.gif)

/cc @n1k0

**Comment by n1k0** [comment]
Nice catch, would you mind filing a new issue for this one?

**Comment by DirtyF** [comment]
OK, done.
